version: '3.8'

services:
  goal-tracker:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./goals.db:/app/goals.db
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/goals', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  goal-tracker-dev:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app/data
      - ./goals.db:/app/goals.db
      - ./frontend/src:/app/frontend/src
      - ./server.js:/app/server.js
    environment:
      - NODE_ENV=development
      - PORT=3000
    profiles:
      - dev
    restart: unless-stopped
